### ISSUE TITLE
pub.dev example page is missing the android permissions required

### ISSUE THREAD

**Issue by guyluz11** [alternadom/WiFiFlutter#100]
The [example tab in pub.dev page of this package](https://pub.dev/packages/wifi_iot/example) does not contain the android permissions that required to insert

Android permissions required that I found 

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

**Comment by daadu** [comment]
This feature/fix has landed on pub.dev with [v0.3.1](https://pub.dev/packages/wifi_iot/versions/0.3.1).
