### ISSUE TITLE
setWiFiAPEnabled fails on Android 10

### ISSUE THREAD

**Issue by yurir** [alternadom/WiFiFlutter#103]
Getting  
`java.lang.NoSuchMethodException: android.net.wifi.WifiManager.setWifiApEnabled [class android.net.wifi.WifiConfiguration, boolean]` 
on Android 10, Galaxy S 10 when trying to call
`WiFiForIoTPlugin.setWiFiAPEnabled(false);` 
or 
`WiFiForIoTPlugin.setWiFiAPEnabled(true);`

Added all possible permission to AndroidManifest.xml. Please advice.

**Comment by daadu** [comment]
This feature/fix has landed on pub.dev with [v0.3.1](https://pub.dev/packages/wifi_iot/versions/0.3.1).
