### ISSUE TITLE
Who is on my WiFi - Pro Spy Tool & Network Scanner App

### ISSUE THREAD

**Issue by sifatullahshah1** [alternadom/WiFiFlutter#107]
i want to create Who is on my WiFi - Pro Spy Tool & Network Scanner app in flutter i have search but found no example or help if any one just give me some help i will be very thank full to him/her

**Comment by daadu** [comment]
There is no general way to "scan and get wifi list in iOS", [check](https://developer.apple.com/reference/systemconfiguration/1614126-cncopycurrentnetworkinfo). 


Closing this issue. Feel free to request re-opening.
