### ISSUE TITLE
Not fully working with Android 10, but how do you connect to a hidden network?

### ISSUE THREAD

**Issue by BillMac4440** [alternadom/WiFiFlutter#108]
I switched over to this library as wifi-configuration was not working on Android 10.  I thought it was working great, but found an issue.  It connects, but seems to lack a route to the network connected into. 
On a secondary question:  I am not sure how to use it if the SSID is hidden.  This a use case of setting up an IoT device.  If not configured, you give the app the serial number and it figures out what the SSID and key would be, connects, then configures the module to the desired network.
All works if the SSID is visible.  I tried calling the function to set that it was hidden before trying to connect, but it throws an exception of trying to set a null object.  If there is a proper method to connect to hidden, please advise.
To test the connectivity issue being debugged with this app, I *can* make the SSID visible, but customer does want it hidden.

**Comment by BillMac4440** [comment]
A few updates to the note: It uses a REST API to setup the module.  I set an old router up like the module and switched from an HTTP.Post to an HTTP.Get to verify a connection as a test.  It could not read the router's main page.  When the app made the connection, a browser would also not work to pull the page.
The connection did get made, and the check to verify the network address was on the correct subnet worked, but there was no route.  In the Android writeup about the API 29 change, they state that if there is another route and you connect to a network with no Internet, that the wifi route will not be used, but I did not have mobile data on at the time, so that should not have been a factor.
Hope this helps to run it down.

**Comment by daadu** [comment]
Does the old router have "Internet capability"? new Android APIs have different APIs for a network with internet and without internet (peer-to-peer, IoT use-cases).

If the router has the internet then, there is a draft PR #99, can you test it against that (instruction in the PR itself) - using `withInternet` flag in `connect` method?

**Comment by BillMac4440** [comment]
The old router was unhooked from Internet as is the IoT module that gets configured.  I set the router up with the same network name, key, and IP of the embedded module's softAP to be able to run an HTTP.Get from it for test purposes. So, in both cases there was no Internet.  I first identified the issue where the HTTP.Post got an error trying to configure the module, so used the router to try to debug.  I will take a look at the PR, probably on Monday.  Thanks!

**Comment by BillMac4440** [comment]
Quick look at the PR, the with Internet is probably opposite of what I need to connect to the softAP of the IoT module.  If that is an option, then OK.  I'll look at it more later.

**Comment by daadu** [comment]
Also try it with `forceWifiUsage`

**Comment by BillMac4440** [comment]
Will do, just to be clear, is that mainline or on the branch?
Sorry for all the questions.  I work in firmware, this flutter is a way to test the embedded code, trying to do my best at getting things working.

**Comment by BillMac4440** [comment]
OK, I setup the pubspec.yaml as given in the instructions to test the branch.  I saw that wihtInternet was now defined and I set it to false as the module's softAP does not have Internet.  The forceWifiUsage was not defined in the connect method.
Android 10 connected to the AP, but there was no route to the REST.Api to setup the module.
On second try to connect, E/AndroidRuntime(25657): java.lang.IllegalStateException: Reply already submitted
Please advise on other possible tests

**Comment by daadu** [comment]
@BillMac4440 No problem with you asking for clarifications!

`forceWifiUsage` is a method itself (not an option in `connect`), call it before making the network call with `await WiFiForIoTPlugin.forceWifiUsage(true)` - this should work with both branches. Also do not forget to not force wiif usage before you disconnect from the network `await WiFiForIoTPlugin.forceWifiUsage(false)` (not doing this will make the network thing go weird, in my experience).

**Comment by BillMac4440** [comment]
Thank you!  I added the forceWifiUsage before and after the post and when done with the connection called disconnect.
It ran great on Android 10 and Android 11.  Only thing yet to solve is the hidden network.
Right now, I set the embedded Linux module to show its SSID, but it should be off.

**Comment by BillMac4440** [comment]
This does not work on Android 9 and down, so I just forked to two branches for old and new.
This is a debug application to test stuff on the module so not a real big deal.

**Comment by daadu** [comment]
@BillMac4440 ideally this shoudl work for <Android9 too, I am using the same approach in my project.

I will look into the hidden SSID problem, probably this weekend if free.

**Comment by daadu** [comment]
Closing this, since #68 is tracking this issue.

**Comment by BillMac4440** [comment]
Perhaps the version should have been bumped after the merge of the hidden SSID.  I had to use the commit number because the previous was also 0.3.2.  Getting setup to test it.

**Comment by BillMac4440** [comment]
Worked great! Configured the module with a hidden soft AP.

**Comment by daadu** [comment]
This fix/feature has landed with [v0.3.3 on pub.dev](https://pub.dev/packages/wifi_iot/versions/0.3.3).

**Comment by BillMac4440** [comment]
Updated my pubspec for v0.3.3 and not the commit.  Works great, thank you so much for all your work on this!
