### ISSUE TITLE
Publish to pub.dartlang.org

### ISSUE THREAD

**Issue by pboos** [alternadom/WiFiFlutter#11]
Can't find this package on https://pub.dartlang.org yet. Are you planning to release it there in the near future? Would make using it a lot easier.

**Comment by pboos** [comment]
Instructions seem to be here: https://flutter.io/developing-packages/#publish

As well I wonder if wifi_iot is the right name for this plugin. Maybe `flutter_wifi` would be better? Sadly `wifi` is already taken. Or maybe write the person behind [wifi](https://pub.dartlang.org/packages/wifi) to collaborate on the plugin? Always better to have one plugin that is maintained by multiple people than having two competing plugins.

**Comment by alternadom** [comment]
I agree for the name, wifi_iot is not the perfect name but it is usually used for IoT :)
It's a shame for the `wifi` name :(
It's a great idea to contact that guy to merge everything, I will send him a message!

**Comment by tommaso1** [comment]
Any news on this?

**Comment by alternadom** [comment]
Nop, I tried to contact the guy at once10301@gmail.com with no success!

**Comment by tommaso1** [comment]
While waiting him.. How can I include it in a project?

**Comment by alternadom** [comment]
You just have to include the repository into your root directory project and modify your "pubspec.yaml" file.. just like any other plugin you could program yourself :)

![Uploading Capture d’écran 2018-08-30 à 13.25.31.png…]()

**Comment by tommaso1** [comment]
Thanks a lot :)

**Comment by cbenhagen** [comment]
@tommaso1 you can also specify a git repo in your `pubspec.yaml`:

```yaml
dependencies:
  proximity_plugin:
    git: https://github.com/alternadom/WiFiFlutter.git
```

**Comment by julienrbrt** [comment]
I think the package can be published :smile:. There is documentation [here](https://dart.dev/tools/pub/publishing) on how to do it @alternadom

**Comment by alternadom** [comment]
Thanks a lot @julienrbrt ;)

**Comment by pboos** [comment]
Awesome! Here the link to pub.dev for those who are too lazy to search:
https://pub.dev/packages/wifi_iot
