### ISSUE TITLE
[ios] iOS v14, requires Local Network permission from user, shoudl be integrated with `forceWifiUsage`

### ISSUE THREAD

**Issue by daadu** [alternadom/WiFiFlutter#110]
This permission is implicitly asked by iOS when the traffic is being sent to the local network. This sometimes does not work properly, for eg - if a HTTP request is made to the device in local network, then if the permission is not given, the request will fail with `SocketException: Connection failed (OS Error: No route to host, errno = 65), address = x.x.x.x, port = 80`.

Ideally the user should check for the permission before calling this request, but iOS does not provide any method to explicitly ask fo r this permission. There is [workaround](https://developer.apple.com/forums/thread/663768) for it, I think we should integrate it with `forceWifiUsage` method (assuming that in IoT cases, wifi usage means access device that is local).

**Comment by daadu** [comment]
@alternadom Do you know any iOS dev that can work on it, I do not know iOS development (although, I could try implementing! but could take a lot of time, and would not be the best implementation)

**Comment by daadu** [comment]
@Niek @at-quannguyen2 @Njuelle @pboos Can you guys give your views on it and/or help implement it.

**Comment by alternadom** [comment]
Sorry @daadu, we don't have that 😢

**Comment by daadu** [comment]
Explicit permission would not be required in debug mode (flutter adds this flutter/flutter#60634, for debug build).

To reproduce this error, use release builds.

**Comment by daadu** [comment]
This has landed in [v0.2.1 on pub.dev](https://pub.dev/packages/wifi_iot/versions/0.2.1).
