### ISSUE TITLE
showWritePermissionSettings unused/not visible?

### ISSUE THREAD

**Issue by fedepell** [alternadom/WiFiFlutter#111]
Hi,
Depending on the Android version the `MANAGE_WRITE_SETTINGS` are needed to configure the WiFi AP. I've noticed that a method to ask for them is already present in the code indeed as [showWritePermissionSettings](https://github.com/alternadom/WiFiFlutter/blob/2e0646419cad65e8316a9aab61b98806916b1897/android/src/main/java/info/whitebyte/hotspotmanager/WifiApManager.java#L50), even if it is not used in any place nor part of the plugin public API.

Is there any reason for this? Could we just, as it is there, publish it so it can be used not to have duplicate code in our app (or dead code in plugin)? 

I will happily do a small PR if deemed useful.

Thanks!
F.

**Comment by daadu** [comment]
I personally haven't used "AP" side of the plugin at all. Looks like the `WifiApManager.java` has history of only one commit!

**Comment by daadu** [comment]
@fedepell It needs a major revamp as far as I know, I initially planned it in #88 but do not have time for it. As you are looking into it, can you go through all methods and test/review them - clean up junk, avoiding use of deprecated APIs - file a PR as a "revamp of access point functionalities on android"?

There are a lot of open issues regarding it. That would be really helpful.

**Comment by fedepell** [comment]
@daadu thanks for the fast feedback!

Indeed I've been studying in the last days the AP part as I'd have a project that would require the App to work as AP with IoT devices connecting (having somehow a preshared or calculable SSID/password). It works pretty fine on pre Oreo devices, but for Oreo and up I'm afraid that some things got changed in a way that precludes many possible functionalities in a IoT view.

Namely AP/hotspot can be still enabled (although in a "local only" mode, so without Internet access), but, of course as far as I could see, the SSID and password are always randomly generated and cannot be changed in any way. This is of course very limiting in my opinion in an IoT usage, as usually IoT devices have a pre-fixed configuration so such a hotspot would not really be of some use, as requires constant and manual reconfiguration.

Details can be of course found in official docs, but a concise response on the topic that seem to be pretty spot-on can be found [here](https://stackoverflow.com/questions/47700717/change-wifi-hotspots-ssid-and-password-in-android-oreo-8-x). 

So at least part of the API would not support post 8 and not sure how much the remaining would be useful. Otherwise of course I'd be glad if I could help if we can find an useful usage.

What do you think?

**Comment by fedepell** [comment]
@daadu I've created a PR for this specific issue as I had already the code locally for my project and that is useful already for pre Oreo devices (so what actual plugin works well with). So I think that would be anyhow useful to have.

Of course let's continue then on the discussion on AP revamp (either here or if you prefeer on another issue) as that is undoubtely something to do one way or another.

Thanks!
F.

**Comment by daadu** [comment]
Opened new issue https://github.com/alternadom/WiFiFlutter/issues/114 for AP functionality revamp on android side.

**Comment by daadu** [comment]
This has landed in [v0.2.1 on pub.dev](https://pub.dev/packages/wifi_iot/versions/0.2.1), do check it out. Thank you @fedepell  for your contribution to this package.
