### ISSUE TITLE
Wifi can not be disconnected completely 

### ISSUE THREAD

**Issue by Creed667** [alternadom/WiFiFlutter#116]
https://stackoverflow.com/questions/66041808/how-to-forget-wifi-completely-with-flutter

i have posted a problem in Stackoverflow related to this plugin...I'm using it for my project where user can connect and disconnect Wifi from the app...now when I'm using `WiFiForIoTPlugin.disconnect();` it does disconnect my device from the wifi for a short amount of times but it automatically connects again....what i can understand it can't forget the password of wifi....can you tell me any way i can do it?

**Comment by daadu** [comment]
use `joinOnce=true` with `connect`

**Comment by fedepell** [comment]
Do you use:
```
static Future<bool> connect(String ssid, {String password, NetworkSecurity security = NetworkSecurity.NONE, bool joinOnce = true})
```
to connect? Do you pass `joinOnce` as `true`? Are you sure the AP is not already in the phone configuration anyway?

Additionally: which version of the plugin are you using and on which platform and version?

**Comment by Creed667** [comment]
@fedepell thank you for your response....I had a lot difficulties with that but now it's solved... i'm using the latest version available in pub dev and my platform is Android 10... on my device the disconnect function doesn't work instead removeNetwork() fucntion works available in wifi iot plugin...
