### ISSUE TITLE
can we read password?

### ISSUE THREAD

**Issue by PrinceGoyal** [alternadom/WiFiFlutter#119]
Can we read password of connected wifi in android and ios, 
another can we read any wifi is public or private and wifi setting is auto connect or not ?

**Comment by talatkuyuk** [comment]
I need this feature. How do we handle/recover/read password for already connected with wi-fi from a mobile phone.

**Comment by Genialngash** [comment]
I also need this feature.
It works on windows .I believe we can also access the stored password value of a WiFi after connecting

**Comment by daadu** [comment]
@talatkuyuk @PrinceGoyal @Genialngash Can you point out ways to do it native platforms (android, ios or wifi)? If so we can think of adding this.

**Comment by rockgecko-development** [comment]
There are apps that can do this on Android, but they require root access. They might be reading the file `/data/misc/wifi/wpa_supplicant.conf` as mentioned here https://stackoverflow.com/a/21334335 (old answer, things may have changed).

**Comment by daadu** [comment]
Looks like not implmentable. Closing this issue. Feel free to request to re-open it.
