### ISSUE TITLE
Readme states that getting BSSID on iOS is not supported

### ISSUE THREAD

**Issue by briansemrau** [alternadom/WiFiFlutter#121]
The readme indicates that getting the BSSID from Wifi networks is unsupported, but it appears this was fixed in #27. Has something changed since that fix, or is the readme out of date?

**Comment by daadu** [comment]
@briansemrau Can you test it and if it works can file PR for readme changes. 

I have started maintaining this package recently, not sure of things that I personally not use.

**Comment by briansemrau** [comment]
I don't have my iOS dev environment set up yet - still just working on android. If I get around to testing it, I'll provide an update then.

**Comment by daadu** [comment]
New API to get  current network info (linked after iOS 12), mentioned here - https://developer.apple.com/reference/systemconfiguration/1614126-cncopycurrentnetworkinfo

**Comment by daadu** [comment]
The fix has landed on pub.dev with v0.3.4.

@briansemrau  Thanks for reporting this bug. Check yourself in README!!
