### ISSUE TITLE
Migrate the package to null safety please.

### ISSUE THREAD

**Issue by EgHubs** [alternadom/WiFiFlutter#122]
Any news? :)

**Comment by daadu** [comment]
@EgHubs I mostly work on the plugin on weekends. Can you look into it and file PR for it?

**Comment by mavyfaby** [comment]
Any updates?

**Comment by daadu** [comment]
I'll try to complete by tomorrow.

**Comment by daadu** [comment]
No promises though.

**Comment by mavyfaby** [comment]
> I'll try to complete by tomorrow.

Thank you :)

**Comment by daadu** [comment]
Added pre-release [v0.3.0-nullsafety.0 on pub.dev](https://pub.dev/packages/wifi_iot/versions/0.3.0-nullsafety.0).

@mavyfaby @EgHubs  Also would recommend to give feedback on it on #124. So that could merge and release as stable

**Comment by daadu** [comment]
Release this in [v0.3.0 on pub.dev](https://pub.dev/packages/wifi_iot/versions/0.3.0)
