### ISSUE TITLE
Warning on 0.3.0

### ISSUE THREAD

**Issue by BillMac4440** [alternadom/WiFiFlutter#125]
../../../flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart:227:13: Warning: Operand of null-aware operation '?.' has type 'NetworkSecurity' which excludes null.
 - 'NetworkSecurity' is from 'package:wifi_iot/wifi_iot.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart').
            security?.toString()?.substring('$NetworkSecurity'.length + 1),
            ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart:245:13: Warning: Operand of null-aware operation '?.' has type 'NetworkSecurity' which excludes null.
 - 'NetworkSecurity' is from 'package:wifi_iot/wifi_iot.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart').
            security?.toString()?.substring('$NetworkSecurity'.length + 1),
Works OK, just gives the warning.

**Comment by EgHubs** [comment]
happens to me also,
here is my error message:

```
Performing hot restart...
Syncing files to device sdk gphone x86 arm...
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart:227:13: Warning: Operand of null-aware operation '?.' has type 'NetworkSecurity' which excludes null.
 - 'NetworkSecurity' is from 'package:wifi_iot/wifi_iot.dart' ('../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart').
            security?.toString()?.substring('$NetworkSecurity'.length + 1),
            ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart:245:13: Warning: Operand of null-aware operation '?.' has type 'NetworkSecurity' which excludes null.
 - 'NetworkSecurity' is from 'package:wifi_iot/wifi_iot.dart' ('../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart').
            security?.toString()?.substring('$NetworkSecurity'.length + 1),
            ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_cache_manager-3.0.0-nullsafety.1/lib/src/storage/cache_info_repositories/cache_object_provider.dart:208:29: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
    final oldDbPath = join((await getDatabasesPath())!, '$databaseName.db');
                            ^
```

**Comment by mavyfaby** [comment]
Fixed issue in #126.

**Comment by wangbo4020** [comment]
**Could move these attribute and ic_launcher to example?
Remove from here, because here is library?**

![image](https://user-images.githubusercontent.com/5559403/113852568-45ccb480-97cf-11eb-96b5-d01b0d55bfbc.png)

**Comment by jwsheen** [comment]
> ../../../flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart:227:13: Warning: Operand of null-aware operation '?.' has type 'NetworkSecurity' which excludes null.
> 
> * 'NetworkSecurity' is from 'package:wifi_iot/wifi_iot.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart').
>   **security?.toString()?.substring('$NetworkSecurity'.length + 1),**
>   ^
>   ../../../flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart:245:13: Warning: Operand of null-aware operation '?.' has type 'NetworkSecurity' which excludes null.
> * 'NetworkSecurity' is from 'package:wifi_iot/wifi_iot.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/wifi_iot-0.3.0/lib/wifi_iot.dart').
>   **security?.toString()?.substring('$NetworkSecurity'.length + 1),**
>   Works OK, just gives the warning.

In Flutter 2.0.4
modify to like this:
**security.toString().substring('$NetworkSecurity'.length + 1),**

works OK.

**Comment by daadu** [comment]
This feature has landed on pub.dev with [v0.3.1](https://pub.dev/packages/wifi_iot/versions/0.3.1).
