### ISSUE TITLE
HTTP requests doesn't work if connection is established via WiFiForIoTPlugin

### ISSUE THREAD

**Issue by oguzhankosar** [alternadom/WiFiFlutter#127]
For my IoT app, I'm trying to connect a WiFi programmatically and then make HTTP request.
So, I used findAndConnect method.
WiFiForIoTPlugin.findAndConnect(ssid, password: password);

Although phone is connected to WiFi successfully, it can't make HTTP request.
There is exclamation mark on WiFi icon in status bar, after WiFi connection.
I tried to setting withInternet flag as true, but it didn't work. And it returns always true even though password is wrong.
I tried to registerWifiNetwork before connecting, but it doesn't work because SDK >= 29.
I tried to setting joinOnce flag as false, but it didn't work.

How can I deal with these problems? I need to stable WiFi connection and make HTTP request successfully.

**Comment by daadu** [comment]
I suggest calling `forceWifiUsage(true)` before making network  calls, this works for me.
