### ISSUE TITLE
LoadWifiList Android 11

### ISSUE THREAD

**Issue by sokunsamnang** [alternadom/WiFiFlutter#133]
Does this WiFi package work on android 11 ? I print debug on function LoadWifiList, there are not show any result.

**Comment by sokunsamnang** [comment]
Found the solution by changed targetSdkVersion to targetSdkVersion 28 and compileSdkVersion to compileSdkVersion 28.

**Comment by kausik-dev** [comment]
This doesn't work for me now. I'm gettin build time error when i change the  compileSdkVersion and targetSdkVersion to 28.
please provide any other solution for this issue
