### ISSUE TITLE
方法名引用警告

### ISSUE THREAD

**Issue by mengsiyitiaojie** [alternadom/WiFiFlutter#135]
![image](https://user-images.githubusercontent.com/55568326/116511828-9ed4c780-a8f9-11eb-8787-227ea8ec9a62.png)

**Comment by daadu** [comment]
@mengsiyitiaojie `WifiForIoTPlugin.getClientList`, is deprecated and there is no way to get this information for the latest versions of  Android.

**Comment by daadu** [comment]
Closing this issue. Feel free to request to re-open.

解决此问题。 随时要求重新打开。(from Google Translate)
