### ISSUE TITLE
Wifi connection with internet doesn't Work - Android 10

### ISSUE THREAD

**Issue by rpenaherrera** [alternadom/WiFiFlutter#136]
Hello there!! I'm trying to use the **connect** and **findAndConnect** functions, but both seems to not validate the wifi credentials (I can write anything in password param but only returns me false when I write a text with less than 8 characters, equal or above of that shows a  dialog to "connect" the phone to the network without internet connection).

**Less than 8 characters returns False**
![image](https://user-images.githubusercontent.com/44820414/117163944-c01a3580-ad89-11eb-8dbe-6778ece71598.png)

**More than 7 characters returns always true for whaterver text I put in password**
![image](https://user-images.githubusercontent.com/44820414/117164266-125b5680-ad8a-11eb-8b1a-a361b1c84288.png)

If I use **withInternet** param (Is the way that I need) with True value, whatever I write in password on both functions always returns me True and it don't stablish any connection like with the flag in Flase.

Always True is use **withInternet** True:
![image](https://user-images.githubusercontent.com/44820414/117166513-0ff9fc00-ad8c-11eb-8820-f847d7a38b8b.png)

I'm working on android 10, connecting to a network with WPA2, any suggestion that I could follow with? 

Thanks for any help!

**Comment by daadu** [comment]
Looks like this a requirement from Android side, although could not find any doc mentioning it on the Internet.

**Comment by daadu** [comment]
Closing this, feel free to request re-open, if find it necessary.
