### ISSUE TITLE
Pretty much nothing works with Android 11

### ISSUE THREAD

**Issue by PlutoHDDev** [alternadom/WiFiFlutter#139]
Hello, when I came across this package I thought this is exactly what I am looking for. 
My plan is to turn on the hotspot of an (Android) smartphone. Of course other functionalities are based on this, but that is the task this package should do.
According to what I read, this should be possible with this package, so I downloaded the repository and tested the example. Unfortunately nothing worked. My smartphone is running Android 11, neither turning the wifi on or off nor turning the hotspot on or off worked. I assume that this is related to the deprecated functions, which only work for older Android SDKs.
Will this change in the near future? Are there any plans regarding this or are there any known alternatives to turn an Android smartphone's hotspot on and off in a Flutter app?
I would be very happy to hear about this so I can start building on this with my idea. If I did anything wrong, then feedback would be great of course, but basically I loaded the example more or less directly onto my smartphone and gave the app location permissions and the permission to change system settings.

**Comment by daadu** [comment]
Hi @PlutoHDDev,

Hotspot/AP functionality in Android are more or less deprecated. However Android have now replaced it with `LocalOnlyHotstpot` (might be getting name wrong). This can let you to "request" a "local only" hotspot - with ssid and password generated by Android itself. This limits the overall functionality of hostpost functionalities.

We have already done discussions on it at #114 #126. Some POV in the discussion suggested completely removing "AP" functionality - as there are not many use-cases that could be fulfilled. If your use-case is of IoT device provisioning, then the "new APIs" are pretty much useless as discussed on those issues. If it is something else - let us know.

Currently,  "requesting local hotspot" is implemented (with `setWiFiAPEnabled`), but getting "info" about the created local hotspot is still unimplemented - it is being tracked at #134, this is mentioned in README - and PR for it are most welcome.

**Comment by PlutoHDDev** [comment]
Thank you very much for the answer. My plan was to turn on a device's hotspot so that a tablet or computer can connect to it and use the smartphone's mobile internet access - just via an app in certain situations. Unfortunately, from what I have read in other issues, this no longer seems to be possible. If I'm wrong, please correct me. It's kind of sad, but that's how things seem to be.
