### ISSUE TITLE
FR: Additional protocol support

### ISSUE THREAD

**Issue by daadu** [alternadom/WiFiFlutter#140]
- Wi-Fi Direct (p2p) - https://developer.android.com/guide/topics/connectivity/wifip2p
- Wi-Fi Aware (NAN) - https://developer.android.com/guide/topics/connectivity/wifi-aware
- Wi-Fi RTT (IEEE 802.11mc FTM) - https://developer.android.com/guide/topics/connectivity/wifi-rtt
- Companion device pairing (with Wifi filters)  - https://developer.android.com/guide/topics/connectivity/companion-device-pairing
- Multipeer Connectivity - https://developer.apple.com/documentation/multipeerconnectivity

**Comment by daadu** [comment]
@mavyfaby @Niek @fedepell @diegotori 

Give me your suggestions on this. 

I mostly use this package so that users can provision IoT devices.

**Comment by mavyfaby** [comment]
Yes, if we implement these functions, it will be great. Some of these features aren't yet implemented in flutter plugins or packages, maybe it's implemented but they lack functionalities. This is the time we implement so that this package will have more capabilities as IoT package.

**Comment by daadu** [comment]
> However, we have to make it very clear in terms of what is supported and in what minimum version of Android. That and making sure that if we don't support it on iOS we make it very clear. Otherwise, all good from my end.

@diegotori That goes without saying, will have tables as we have in the current README.

**Comment by fedepell** [comment]
@daadu sounds of course good to me! Not a small work to do and for sure (as already said) it may be hard to make it supported also on iOS (ie. AFAIK iOS has another similar peer-to-peer protocol called AirDrop or so). 

Note for wifi-direct as I already looked once around this also exists: https://github.com/mintware-de/flutter_p2p

**Comment by daadu** [comment]
Additional Doc for iOS - https://developer.apple.com/library/archive/qa/qa1942/_index.html - defines different Wifi APIs and there use cases in iOS

One issue we might have is the plugin size increasing - I think the better idea would be to maintain it as separate plugin under same repo (like [firebase](https://github.com/FirebaseExtended/flutterfire) or [plus_plugins](https://github.com/fluttercommunity/plus_plugins)). In this case user can pick and choose which functions he wants. Also it would be easier to maintain it - we can assign codeowner and what not - so that, someone actively using that plugin is responsible for it.

Let me know your views.

**Comment by daadu** [comment]
The above includes, breaking the current plugin too - into two - one for WIFi STA and one for WiFi AP/Hostpost.

**Comment by daadu** [comment]
Since we are talking reforms I have added another issue #143 that could cause breaking change. Give your views there too.

**Comment by daadu** [comment]
@fedepell 

I contacted @mintware-de (maintainer of [flutter_p2p](https://github.com/mintware-de/flutter_p2p)), He is ok with us merging and maintaing `flutter_p2p`.

**Comment by daadu** [comment]
@fedepell p2p in iOS is limited to connecting to Apple Devices only. Since the underlying protocol is not disclosed.

More docs related to MPC:
- https://www.toptal.com/ios/collusion-ios-multipeerconnectivity
- https://developer.apple.com/documentation/multipeerconnectivity

**Comment by Soockee** [comment]
Hi folks,
I am a flutter noob. Since I want to implement multi-or trilateration with the WiFi_RTT protocol, while trying out flutter, I require this for my use case. 

How difficult/how much time are you estimating for the implementation of RTT? :)

If this is too deep/hard, I won't even try and go for a android native app, even tho I want to try to use flutter :)

**Comment by fedepell** [comment]
Looking at https://developer.android.com/guide/topics/connectivity/wifi-rtt it doesn't seem that there is too much stuff to do IMO, it's basically wrapping the parts described from **Setup** to **Interpret ranging results** sections. The fact is that you need a device (and an access point) that supports it to do the development, but I guess you should have those since you are asking :)

**Comment by daadu** [comment]
Hello everyone,

In order to maintain the project as it grows, I have decided to break `wifi_iot` to multiple plugins [#186]. New protocols will have there own plugins - as of now have planned `wifi_aware` [#191] and `wifi_rtt` [#192].

I am closing this issue and further discussion should be done on those threads.
