### ISSUE TITLE
[breaking] reduce repo size from 190mb

### ISSUE THREAD

**Issue by daadu** [alternadom/WiFiFlutter#143]
The current github repo has large files (`build/` dir, etc) in the history, this has bloated the repo size.

[bfg](https://rtyley.github.io/bfg-repo-cleaner/) tool could be used to clean this history up. But this would have breaking changes - the forked/ repo still have those old commit and any PR from those repos will bring back those commit. This could be resolved in (on of the) two ways:

1. force push to the current repo (`master` branch), not accepting the PR coming from those repo, suggesting them to re-fork/re-clone and refile the PR.
   - since we have small number of active contributor, this wont be much of an issue.
   - will retain stats like - star, watch, etc.
   - github might take some time to do garbage collect
2. new repo (say `FlutterWIfi`) with cleaned up history - move all issues from here to the new one - archiving the current repo with instruction suggesting the active repo is something else.

This issue is open for discussion and might not be worked upon, if that is agreed upon.

**Comment by daadu** [comment]
CC: @alternadom

**Comment by alternadom** [comment]
Hi,
The option 1 seems to be good for us!
What is your opinion @daadu about all of this ?
Thanks for all you work here by the way 😉

**Comment by fedepell** [comment]
I guess for option 1 you can follow something like described here: https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by daadu** [comment]
@alternadom I think I do not have proper permission to update all the refs

These the logs
```
Enumerating objects: 1402, done.
Writing objects: 100% (1402/1402), 607.95 KiB | 202.65 MiB/s, done.
Total 1402 (delta 0), reused 0 (delta 0)
remote: Resolving deltas: 100% (606/606), done.
To https://github.com/alternadom/WiFiFlutter.git
 + 2ce983a...c6f9c68 master -> master (forced update)
 ! [remote rejected] refs/pull/1/head -> refs/pull/1/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/112/head -> refs/pull/112/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/113/head -> refs/pull/113/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/115/head -> refs/pull/115/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/118/head -> refs/pull/118/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/12/head -> refs/pull/12/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/124/head -> refs/pull/124/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/126/head -> refs/pull/126/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/13/head -> refs/pull/13/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/14/head -> refs/pull/14/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/141/head -> refs/pull/141/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/145/head -> refs/pull/145/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/146/head -> refs/pull/146/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/19/head -> refs/pull/19/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/21/head -> refs/pull/21/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/27/head -> refs/pull/27/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/28/head -> refs/pull/28/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/30/head -> refs/pull/30/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/31/head -> refs/pull/31/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/36/head -> refs/pull/36/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/38/head -> refs/pull/38/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/39/head -> refs/pull/39/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/44/head -> refs/pull/44/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/48/head -> refs/pull/48/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/5/head -> refs/pull/5/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/50/head -> refs/pull/50/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/51/head -> refs/pull/51/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/52/head -> refs/pull/52/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/53/head -> refs/pull/53/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/54/head -> refs/pull/54/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/55/head -> refs/pull/55/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/56/head -> refs/pull/56/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/6/head -> refs/pull/6/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/65/head -> refs/pull/65/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/71/head -> refs/pull/71/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/86/head -> refs/pull/86/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/87/head -> refs/pull/87/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/88/head -> refs/pull/88/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/9/head -> refs/pull/9/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/95/head -> refs/pull/95/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/99/head -> refs/pull/99/head (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/alternadom/WiFiFlutter.git'
```

**Comment by daadu** [comment]
Some information about this:

- Files/Folderes to be cleaned from history
  - dir `example/build/`
  - dir `example/ios/Flutter/flutter_assets/`
  - dir `example/ios/Flutter/App.framework/`
  - dir `example/ios/Flutter/Flutter.framework/`
  - file `example/ios/Flutter/app.flx`
  - file `example/ios/Flutter/app.zip`
  - dir `example/android/.gradle/`
- `bfg` command to be executed to clean
  - `java -jar bfg-1.14.0.jar --delete-folders "{build,flutter_assets,flutter_assets,App.framework,Flutter.framework,.gradle}" --delete-files "{app.flx,app.zip}" WiFiFlutter.git`

**Comment by daadu** [comment]
Looks like that `git push` worked, it pushed to `master` but failed with "hidden ref" (read-only PR ref).

The repo size is now - `645.72 KiB`!!

Attaching `bfg` report for this operation. Just in case.
[19-08-15.zip](https://github.com/alternadom/WiFiFlutter/files/6466688/19-08-15.zip)


Also, I have backed up the original repo on my machine, just in case, will push that if required (Although, I don't think we will!!).


Request all maintainer to re-fork/re-clone the repo and work on it rather that old. Keep a copy of old one just in case!

**Comment by daadu** [comment]
Keeping a fork (pre-cleanup) as a backup for old repo - https://github.com/daadu/WiFiFlutter-143-pre-bfg

**Comment by daadu** [comment]
Closing this issue. Feel free to request re-opening.
