### ISSUE TITLE
wifi connect with out internet 

### ISSUE THREAD

**Issue by vishnuvarthann** [alternadom/WiFiFlutter#153]
I can able to connect to specific network with ssid and password ,but after successfulLy connected i canable to see it not connect with internet , any work around if i try with  withInternet:false, it does not show teh popup and if set true it does ,

  WiFiForIoTPlugin.connect("xccxcxcxxxcx",
          password: "nsdvsdvasdv",
          withInternet:false,
          joinOnce: true,
          security: STA_DEFAULT_SECURITY);
    }

**Comment by daadu** [comment]
after connecting try `forceWifiUsage(true)` before making networking request.

Make sure you disbale it again after disconencting to the network.

**Comment by vishnuvarthann** [comment]
was try to connect it with ssid and password . it works . when i was try with another ssid and pasword . which has no internet connection  and it try to connect and disconnect .

**Comment by vishnuvarthann** [comment]
if i try to connect with specifi c ssid and password after successfully connected but without internet . 

why it should show in saved network list  ,if an ssid is succesfully connect it should display in save network  i think .
forcewifiusag(true) where we need to call after hit WiFiForIoTPlugin.connect
  _selectedItem(resultssid, BuildContext context) async {
    Scaffold.of(context).showSnackBar(SnackBar(
      content: Text(_connectionStatus,
          style: TextStyle(color: Colors.white, fontSize: 16)),
      duration: Duration(seconds: 3),
      backgroundColor: Colors.red,
    ));

  //WiFiForIoTPlugin.forceWifiUsage(true);
    if (resultssid != null) {
      WiFiForIoTPlugin.forceWifiUsage(true);
      WiFiForIoTPlugin.connect("JioFi_2434ABF",
          password: "nuxfe9ae7f",
          withInternet:false,
          joinOnce: false ,
          security: STA_DEFAULT_SECURITY);
    }
    

  WiFiForIoTPlugin.forceWifiUsage(true);

**Comment by daadu** [comment]
In latest Android version, connect network from WIfi does not add to the saved wifi list.

You might want to check `registerNetwork` for that.


And in above example you need to `await` for `connect` method, then call `forceWifiUsage`

**Comment by gamelaster** [comment]
Hi @daadu
> In latest Android version, connect network from WIfi does not add to the saved wifi list.

I don't think it's true. The WiFi Launcher app (which is open-source) does it: (Android 11, OnePlus 6T)
![image](https://user-images.githubusercontent.com/1665373/134762940-6d78c171-e301-47af-a7bb-dfe2a53b402a.png)

I found this [code](https://github.com/borconi/WifiLauncherforHUR/blob/5eb1fc7b9f9b35182b96e4c50838b02145e1608a/app/src/main/java/com/borconi/emil/wifilauncherforhur/services/WifiService.java#L224) which looks pretty similar to code in this library, although, didn't find the difference ☹️

**Comment by SabarishChungath** [comment]
```
WiFiForIoTPlugin.forceWifiUsage(true);
await WiFiForIoTPlugin.connect(
   parsedData.networkName!,
   password: parsedData.password,
   joinOnce: false,
   security: networkSecurity,
   withInternet: false,
   isHidden: isHidden
);
```


I have added the above it successfully connects to WIFI but without internet connection
Am I doing anything wrong here ?

**Comment by gamelaster** [comment]
@SabarishChungath force WiFi usage **after** the connection.
