### ISSUE TITLE
OS Error: Network is unreachable

### ISSUE THREAD

**Issue by fernando-s97** [alternadom/WiFiFlutter#155]
Hi!

I can successfully connect to one AP device from my Android, but once I'm connected, I navigate to another screen and from there I can make some http requests, but all of them fail with `SocketException: Connection failed (OS Error: Network is unreachable, errno = 10`.

This only happens if connect programatically. If I manually connect from the wifi settings and get back to the app, everything works fine.

Any clue on why is that?

Oh, by the way, after I navigate to the other screen, I can see that the WiFi is still connected to the AP.

**Comment by daadu** [comment]
You need to use `forceWifiUsage(true)`, before making request and disable it once done.

**Comment by fernando-s97** [comment]
@daadu I'll try this ASAP. Thanks

**Comment by fernando-s97** [comment]
@daadu That worked like a charm. Thanks again!
