### ISSUE TITLE
.isEnabled and .isConnected returning false

### ISSUE THREAD

**Issue by troyredder** [alternadom/WiFiFlutter#156]
We are using these two flags to confirm a connection with iOS devices which has been working as expected until 0.3.4 release.  Both flags are never returning true within that release.

**Comment by daadu** [comment]
What iOS device are you testing it?

**Comment by daadu** [comment]
Also if you got time can you through #150 which was added to v0.3.4, to see if what can be the bug introduced in this version.

**Comment by DominikStarke** [comment]
Should be fixed by https://github.com/alternadom/WiFiFlutter/pull/175 this is due to isEnabled and isConnected's reliance on getSSID which isn't working in the current version.

**Comment by daadu** [comment]
Closing this as fixed with #175. It has landed of pub.dev with v0.3.7

@troyredder Thanks for reporting the bug, check yourself on README.

**Comment by xiki808** [comment]
isEnabled is returning false, using iOS 15.31 and plugin v 0.3.15+2

**Comment by daadu** [comment]
`isEnabled` in iOS checks where `getSSID != null` - there is no official API for it.
