### ISSUE TITLE
BSSID on iOS

### ISSUE THREAD

**Issue by minhvn** [alternadom/WiFiFlutter#16]
`Hi` @alternadom I saw you got SSID on ios with key kCNNetworkInfoKeySSID. How can got bssid with kCNNetworkInfoKeyBSSID. 
Can add 

```
guard let interfaces = CNCopySupportedInterfaces() as? [String] else { return nil }
        let key = kCNNetworkInfoKeyBSSID as String
        for interface in interfaces {
            guard let interfaceInfo = CNCopyCurrentNetworkInfo(interface as CFString) as NSDictionary? else { continue }
            return interfaceInfo[key] as? String
        }
        return 
```
to body of 
`private func getBSSID(result: FlutterResult)`

Thank you.

**Comment by alternadom** [comment]
Hi @minhvn,

I'm not sure that it work... iOs is pretty restricted!
You can test by yourself and tell us what is your result!

Thanks,

**Comment by TFTcoin** [comment]
> Hi @minhvn,
> 
> I'm not sure that it work... iOs is pretty restricted!
> You can test by yourself and tell us what is your result!
> 
> Thanks,

HI, In Iphone 4s with old ios version, can got BSSID, but didnt get IP address.

**Comment by minhvn** [comment]
Can get BSSID, but cannot get IP on ios.

**Comment by minhvn** [comment]
Hi @alternadom, I see on doc of apple, test and it's work on iOS 12(iPhone 7).

https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo#parameters

> To use this function in iOS 12 and later, enable the Access WiFi Information capability for your app in Xcode. When you enable this capability, Xcode automatically adds the Access WiFi Information entitlement to your entitlements file and App ID. 

![screen shot 2018-11-12 at 2 53 25 pm](https://user-images.githubusercontent.com/187747/48333640-c59bd680-e68a-11e8-914e-2ee3d53344e4.png)

**Comment by alternadom** [comment]
Oh thanks @minhvn ! I will look into it as soon as possible ;)

**Comment by TheKvikk** [comment]
Hi @alternadom you'll also need to purchase iOS Developer license – without it, enabling Access WiFi Information will change nothing.

Also anyone using this package will need iOS Developer license to access BSSID and few other things.
