### ISSUE TITLE
I cannot get the SSID of current connected Wifi on ios 14.3 and 14.6. It is returning null value.

### ISSUE THREAD

**Issue by starsoft4u** [alternadom/WiFiFlutter#161]

**Comment by DominikStarke** [comment]
Same issue:
https://github.com/alternadom/WiFiFlutter/issues/105

Seems like NEHotspotNetwork.fetchCurrent either doesn't work as expected, or has weird constraints that aren't documented.

**Comment by daadu** [comment]
This has landed on pub.dev with [v0.3.7](https://pub.dev/packages/wifi_iot/versions/0.3.7)

@starsoft4u Thanks for reporting this, check yourself on README!
