### ISSUE TITLE
[Android] loadWifiList fails if location permission is requested at the same time

### ISSUE THREAD

**Issue by Hallot** [alternadom/WiFiFlutter#167]
What: Calling `WiFiForIoTPlugin.loadWifiList()` if location permission hasn't been granted yet fails on Android.

How to reproduce: Using the example, clicking on "Scan" will fail the first time. The permission prompt will appear, and even if the permission is granted, the scan will fail and no wifi list will appear. Clicking "Scan" a second time will work (assuming the permission was granted).

Root cause: The root cause seems to be that in `loadWifiList` in `WifiIotPlugin.java`, `moWiFi.startScan();` is called without waiting for the permission prompt to be completed. Thus the scan will start before permission is granted, and thus fail.

**Comment by daadu** [comment]
@Hallot This has been a long-standing issue (not with just with `loadWifiList`, but any method that "requires location permission").

It would be great if you file PR to correct this behaviour, it seems non-trivial last time I checked, but I could be wrong - so give it a try!

I for my project use another plugin (like [`location_permissions`](https://pub.dev/packages/location_permissions)) to check if permission is granted before calling it.

**Comment by Hallot** [comment]
@daadu I've given it a shot, it fixes the problem and hopefully breaks nothing.  
The Android API is pretty horrible honestly, it would be so much nicer to be able to do something like `permissionResult = await requestPermissions()` instead of having to put everything in a gigantic callback, but oh well.
