### ISSUE TITLE
Why there is no comment

### ISSUE THREAD

**Issue by yongjieYuan** [alternadom/WiFiFlutter#172]
Can you provide some comments in the example, and where can I get the about api document, I have been reading the example for a day, it’s too much work

**Comment by daadu** [comment]
@yongjieYuan Discussion/work on revamping example is being tracked on #170. Please give you input there. Closing this issue, therefore.

**Comment by yongjieYuan** [comment]
Thanks for your responsive, I should spent much  time on searching this plugin, and I  will focus this project continually.

**Comment by yongjieYuan** [comment]
Thanks for your responsive, I should spend much time on searching this plugin, and I will focus this plugin continually.
