### ISSUE TITLE
Erro when build with Permissions

### ISSUE THREAD

**Issue by pedrojalbuquerque** [alternadom/WiFiFlutter#173]
final bool wasPermissionGranted = grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED;

Erro not find bool, the correct is:

final boolean wasPermissionGranted = grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED;

on WIfiIotPlugin.java, line 192.

Check to fix it.

Thanks

**Comment by zhanlijia** [comment]
me too

**Comment by JAICHANGPARK** [comment]
I have same problem

**Comment by JAICHANGPARK** [comment]
android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java:192: error: cannot find symbol
        final bool wasPermissionGranted = grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED;

**Comment by daadu** [comment]
This has landed on pub.dev with v0.3.6.

Thanks for reporting it.

**Comment by JAICHANGPARK** [comment]
@daadu Thanks !
