### ISSUE TITLE
Podfile is out of date Issue

### ISSUE THREAD

**Issue by martinkong0806** [alternadom/WiFiFlutter#179]
Hi there,
I was trying to fork the repository and run the example, but i countered an issue that stops my app building.

To reproduce the problem:
Run  example/main.dart in Android Studio

Here is the log: 
![Screenshot 2021-10-07 at 13 03 22](https://user-images.githubusercontent.com/50043994/136380628-05ce38a1-548e-4874-94c2-9e0233c01ce0.png)

No issues when running `flutter doctor` : 
![Screenshot 2021-10-07 at 13 05 58](https://user-images.githubusercontent.com/50043994/136380922-9653efc8-2901-478e-bbac-45f6c75fd93b.png)

**Comment by daadu** [comment]
@martinkong0806 The example app is outdate and needs a revamp.

The discussion around it is being tracked at  #170. Feel free to join and contribute there.

Closing this issue.
