### ISSUE TITLE
removeWifiNetwork could delete other networks than the desired

### ISSUE THREAD

**Issue by csanz91** [alternadom/WiFiFlutter#18]
I have seen this issue in the Android .java I haven't researched about the iOS version.

When the ssid passed to be deleted is being compared with the existing networks, it is only verified that the begining of the ssid network matches.
https://github.com/alternadom/WiFiFlutter/blob/4dbbad817981b65f780acdb0ffeac14dcec99e68/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java#L659
 For example, if I have the networks:
- wifinetwork
- wifinetwork1
- wifinetwork2
And I want to delete the station 'wifinetwork' it is possible that any of the three networks will be removed.
It can be solved by checking the full ssid.

**Comment by alternadom** [comment]
Please don't create 2 threads about the same problem.. thanks!

**Comment by csanz91** [comment]
I have confirmed what you have said in the other issue with an Android device. The networks created in the settings, i.e. outside the application, cannot be removed using this method, therefore there is no risk of removing a user wifi network.
However I think there should be a comment or any kind of documentation explaining this behaviour, that any network created by the app that begins with the ssid passed to the removeWifiNetwork method will be removed. I think if you don't delve deeper into the code is not easy to find out about this behaviour and it can lead to unexpected results.
