### ISSUE TITLE
android connect release mode with obfuscate not working

### ISSUE THREAD

**Issue by nathan2day** [alternadom/WiFiFlutter#185]
This is an Android only issue.

findAndConnect works in debug and release mode:

    WiFiForIoTPlugin.findAndConnect(network_ssid,
               password: password)

connect works only in debug mode:

    WiFiForIoTPlugin.connect(network_ssid,
               security: NetworkSecurity.WPA,
               password: password)

I build a release using:

    flutter build -v apk --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols

I've compared findAndConnect and connect in WifiIotPlugin.java, the main difference being that the security type is extracted from the wifi scan result, rather than in the case of "connect" being passed as a parameter.

Looking at connect in wifi_iot.dart the security parameter is converted to a string:

    "security": security.toString().substring('$NetworkSecurity'.length + 1)

NetworkSecurity is an enum, obfuscation will scrabble the enum's strings, so the security.toString() will not return "WPA" as expected on android with obfuscation.

My app handles this kind of situation, using a mapping from enum values to strings, as so:

    enum MainContent {
      home,
      menu,
    }

    Map<MainContent, String> breadcrumbTitles = {
      MainContent.home: "Home",
      MainContent.menu: "Menu",
    };

    Queue breadcrumbs = Queue<MainContent>();
    String showTitle = "";

    if (breadcrumbs.isNotEmpty) {
      selectedContent = breadcrumbs.last;
      showTitle = breadcrumbTitles[selectedContent];
    }

Hope that helps, both to fix and other who may have experienced the same.

https://github.com/flutter/flutter/issues/58090

**Comment by daadu** [comment]
@nathan2day I have opened PR that fixes this at #207. Please review and test against it.

**Comment by daadu** [comment]
Released with [v0.3.11](https://pub.dev/packages/wifi_iot/versions/0.3.11). Thanks @nathan2day for reporting, check yourself in package readme!
