### ISSUE TITLE
open failed: EACCES (Permission denied) ??

### ISSUE THREAD

**Issue by pheromone** [alternadom/WiFiFlutter#202]
E/class info.whitebyte.hotspotmanager.WifiApManager$1( 7468): java.io.FileNotFoundException: /proc/net/arp: open failed: EACCES (Permission denied)

  wifi_iot: 0.3.8

**Comment by daadu** [comment]
hotspot features are not maintained anymore - as it is using "private Android APIs".

Plugin currently only maintains for Android API >= 29.
