### ISSUE TITLE
Not connecting to wifi

### ISSUE THREAD

**Issue by Kevintjeb** [alternadom/WiFiFlutter#25]
Hello,

I want to let the device connect to a given SSID and Pasword. I have used the connect function, this does however not connect the device to the network. It does add the network, but it is unsuccessful in connecting.

Manually connecting to the network is successful. I have also tried using an unprotected Access Point, with no luck.

To make sure I am using the library correctly, how should I connect to a wifi access point if I know the SSID and password?

`WifiIotPlugin.connect("testssid")`

**Comment by komputerboy** [comment]
same here. how to connect specific wifi/acces point that i already know?

**Comment by pboos** [comment]
```
WiFiForIoTPlugin.connect(
      WIFI_SSID,
      password: WIFI_PASSWORD,
      security: NetworkSecurity.WPA,
    );
```

**Comment by sokunsamnang** [comment]
How to get dynamic password by input password from app not staic in code??
