### ISSUE TITLE
Get SSID & Password of the connected network

### ISSUE THREAD

**Issue by assafb81** [alternadom/WiFiFlutter#26]
Hi,
Great package!

1. Is it possible to get the ssid and the **password** of the connected network in iOS?
2. Is it possible to get a full list of the available networks in iOS?

Thanks

**Comment by alternadom** [comment]
In my opinion, for the short answers : No & no! 

If I'm wrong, I'm interested in the solution ;)

**Comment by assafb81** [comment]
thanks!
