### ISSUE TITLE
MAC filtering

### ISSUE THREAD

**Issue by yhua537** [alternadom/WiFiFlutter#3]
not sure if this will help, I found this undocumented workaround from [stackoverflow](https://stackoverflow.com/questions/17419847/how-can-i-get-the-number-of-devices-connected-through-the-phones-access-point?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa). Someone can claim the ownership of this. But i think this only works in Android as iPhone is unlikely let you do this. 

`
    public static String getHardwareAddress(String ip) {
        final String MAC_RE = "^%s\\s+0x1\\s+0x2\\s+([:0-9a-fA-F]+)\\s+\\*\\s+\\w+$";
        final int BUF = 8 * 1024;

        String hw = "00:00:00:00:00:00";
        BufferedReader bufferedReader = null;
        try {
            if (ip != null) {
                String ptrn = String.format(MAC_RE, ip.replace(".", "\\."));
                Pattern pattern = Pattern.compile(ptrn);
                bufferedReader = new BufferedReader(new FileReader("/proc/net/arp"), BUF);
                String line;
                Matcher matcher;
                while ((line = bufferedReader.readLine()) != null) {
                    matcher = pattern.matcher(line);
                    if (matcher.matches()) {
                        hw = matcher.group(1);
                        break;
                    }
                }
            } else {
                Log.e(TAG, "ip is null");
            }
        } catch (IOException e) {
            Log.e(TAG, "Can't open/read file ARP: " + e.getMessage());
            return hw;
        } finally {
            try {
                if(bufferedReader != null) {
                    bufferedReader.close();
                }
            } catch (IOException e) {
                Log.e(TAG, e.getMessage());
            }
        }
        return hw;
    }
`

**Comment by alternadom** [comment]
Hi,

By reading "/proc/net/arp", you are reading the current users, already connected to your system.. so they weren't filtered!
I tried to manipulate some files on HOSTAPD but without success :(

Thanks for your help!

**Comment by yhua537** [comment]
yes, it is connected, otherwise it will not have IP. you can let them connect first to get their Mac and  block the given ip after that. Note that Mac address can be change so it is still not secure for your IoT.

**Comment by alternadom** [comment]
In fact, at first, I wanted to the IoT to connect to my phone through the hotspot and only my IoT! So, just one device should be connected.. but I stopped dreaming, today I was working on the iOS part... #headache

**Comment by yhua537** [comment]
i am taking different approach, phone connect to the device wifi and then setup. and looks like your loadWifiList() gives empty list all the time, will keep trying.

**Comment by alternadom** [comment]
In fact, with today in dev on iOS, we are going to connect in WiFi directly, not passing by a hotspot step which is impossible on iOS device..
I will push my changes after testing :)

**Comment by alternadom** [comment]
I had the same problems with empty list because my WiFi was disabled.. I'm pushing some updates today, tell me if you still have the problem ;)

**Comment by yhua537** [comment]
Looks like we have 3 problem here, currently still stuck with #1


1. Need to request permission if version is M or above. Copy from my old project: 

`
            if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && ContextCompat.checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED){
                mContext.requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION}, PERMISSIONS_REQUEST_CODE_ACCESS_COARSE_LOCATION);
                

            }
`
2. Once permission is granted, need to add moWiFi.startScan(); before getting the result. I am trying to understand how this will work in Flutter:
`    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        if (wifiManager != null && requestCode == PERMISSIONS_REQUEST_CODE_ACCESS_COARSE_LOCATION) {
            for (int grantResult : grantResults) {
                if (grantResult != PackageManager.PERMISSION_GRANTED) {
                    return;
                }
            }
            wifiManager.startScan();
        }
    }`
3. The scan took a while to return so we need to setup a event channel like what's in the[ connectivity plugin](https://github.com/flutter/plugins/blob/master/packages/connectivity/lib/connectivity.dart). 
_onConnectivityChanged = _eventChannel
          .receiveBroadcastStream()
          .map((dynamic event) => _parseConnectivityResult(event));

**Comment by alternadom** [comment]
Hi @yhua537, can we close the issue now ?

**Comment by yhua537** [comment]
Yes, sure! closed.
