### ISSUE TITLE
Is location permission necessary?

### ISSUE THREAD

**Issue by daadu** [alternadom/WiFiFlutter#32]
I noticed the Manifes.xml for android specifying Location permission. Is it necessary? Because I will have to ask the user to grant this permission beforehand.

**Comment by daadu** [comment]
any update?

**Comment by daadu** [comment]
@alternadom

**Comment by alternadom** [comment]
Hi,
Thanks for asking, I'm not sure about this.. If you remove it, does it still work ?!
Maybe you will have your answer after testing!
Regards

**Comment by daadu** [comment]
Check issue #40. This permission is at least required for disconnecting from a WiFi network.

**Comment by julienrbrt** [comment]
Yes it is necessary according to the Android Developers documentation: https://developer.android.com/guide/topics/connectivity/wifi-scan

**Comment by alternadom** [comment]
Thanks for your help!

**Comment by julienrbrt** [comment]
@daadu Should not this issue be closed?

**Comment by daadu** [comment]
@julienrbrt Yes.
