### ISSUE TITLE
MissingPluginException on iOS

### ISSUE THREAD

**Issue by R1cs1KING** [alternadom/WiFiFlutter#33]
Hi all!
I have encountered an issue when I am trying to connect to WiFi on iOS (on Android it works).
This is the error I get:
> flutter: MissingPluginException : MissingPluginException(No implementation found for method setEnabled on channel wifi_iot)

And this is the code I am using to connect:
`WiFiForIoTPlugin.connect(ssid, password: password, security: NetworkSecurity.WPA);`

Thanks for your help in advance!

**Comment by R1cs1KING** [comment]
I am not sure about it, but I am not sure about in SwiftWifiIotPlugin.swift this method:
`private func setEnabled(call: FlutterMethodCall, result: FlutterResult) {
        let arguments = call.arguments
        let state = (arguments as! [String : Bool])["state"]
        if (state != nil) {
            print("Setting WiFi Enable : \(((state ?? false) ? "enable" : "disable"))")
            result(FlutterMethodNotImplemented)
        } else {
            result(nil)
        }
    }`
should result `FlutterMethodNotImplemented` in the first case.

**Comment by Niek** [comment]
Same problem here, ``connect()`` calls ``setEnabled(true)`` which causes this issue. What is the best fix? I assume ``setEnabled(true)`` shouldn't be called on iOS?

**Comment by nmbus** [comment]
Same here, the connect function does not work. Commenting out the call to setEnabled in wifi-iot.dart does not seem to fix the issue either.

**Comment by daadu** [comment]
I have added PR that does what @Niek mentioned. It solves the problem for me.

@Niek @R1cs1KING Please confirm by using my fork repo to test (check below snippet to do that) so that it can be merged.

```yaml
dependencies:
  flutter:
    sdk: flutter
  ...
  wifi_iot: #^0.1.1
    git:
      url: https://github.com/daadu/WiFiFlutter.git
```

**Comment by Niek** [comment]
Yep that's the fix @daadu

**Comment by daadu** [comment]
@alternadom  Please merge.

**Comment by BenoitDuffez** [comment]
I still have this problem on iOS14 emulator. The fix is present. What's wrong?

**Comment by daadu** [comment]
sacn and getting wifi list is not possible in iOS (AFAIK)

**Comment by BenoitDuffez** [comment]
Yes indeed, as I found out after posting. This baffles me but I'll find another way. Thanks for confirming!

**Comment by pyon123** [comment]
I also have a problem.
I am trying to connect wifi on iOS phone using wifi_iot library.

WiFiForIoTPlugin.connect(ssid, password: password, security: NetworkSecurity.WPA);

There is no MissingPluginException and it doesn't seem to publish any error.

But I can't connect to other wifi with my Phone. (Android works fine.)
Does anyone solve this issue?

**Comment by daadu** [comment]
@pyon123  Did you add proper entitlements (this part is missing in README) - `Hotspot Configuration` and  `Access WiFi Information` ?

**Comment by pyon123** [comment]
@daadu Thanks for your kind reply.
I am not sure I configure it successfully. This is all what I do.
![image](https://user-images.githubusercontent.com/66934494/118400357-daaab380-b693-11eb-9b53-7b60c8cd149a.png)

it is working fine in Android 9.0. But not working iOS. My iOS version is 12.5.3.
I made ESP32 device as an access point and trying to connect to that device with my phone.
So no need to Hotspot configuration on my phone. Just want to access the device.

Please let me know your answer.

**Comment by daadu** [comment]
@pyon123 "Hotspot" in iOS is not "Accesspoint (Hotspot) in WLAN", is the underlying library name, that the package uses.

Additional setups, that are not documented in README, are as following, please follow them and let me know if it works.

![Screenshot from 2021-05-16 20-39-11](https://user-images.githubusercontent.com/4963236/118402308-f5c2f680-b686-11eb-8251-577b9dd977b6.png)

**Comment by ngmduc2012** [comment]
<img width="901" alt="Screen Shot 2022-04-21 at 17 42 23" src="https://user-images.githubusercontent.com/56816382/164441890-f85245ea-3ed7-49df-b92a-de662d17bcc5.png">
 It works for me. i added 3 them

**Comment by selcuksenel** [comment]
I think the plugin no longer works on iOS.(flutter: Cannot get scanned results: CanGetScannedResults.notSupported) When I run the wifi scan sample code, I encounter such a message. You should update the documents, you are causing a lot of people to waste their time this way sir!!
