### ISSUE TITLE
Problem getting SSID on iOS.

### ISSUE THREAD

**Issue by dmvvilela** [alternadom/WiFiFlutter#34]
It just returns null.. am i missing something ?

**Comment by alternadom** [comment]
I think you missed the permission section.. check it please!

**Comment by dmvvilela** [comment]
I just saw that i have to make a new provisioning profile right? This is crazy! But ok.. i will try it! Thanks. Also.. does apple complain (and maybe dont let my app be submited to the app store) if i use the connect to selected wifi api (with ssid and password)?

**Comment by alternadom** [comment]
I'm not sure what you are asking.. but we didn't had problems to submit our app to the app store!

**Comment by dmvvilela** [comment]
Awesome, thanks!
