### ISSUE TITLE
Wrong thread

### ISSUE THREAD

**Issue by mrm** [alternadom/WiFiFlutter#35]
Since the new flutter version I'm getting the following crash:
```
E/AndroidRuntime(25525): FATAL EXCEPTION: Thread-5
E/AndroidRuntime(25525): Process: com.tt.tga, PID: 25525
E/AndroidRuntime(25525): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-5
E/AndroidRuntime(25525): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(25525): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/AndroidRuntime(25525): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
E/AndroidRuntime(25525): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(25525): 	at com.alternadom.wifiiot.WifiIotPlugin$5.run(WifiIotPlugin.java:538)
```

It appears results need to be passed back to the main thread and  `poResult.success(connected);` should be called from there?

**Comment by matteobertino** [comment]
I've had the same issue with flutter 1.7+ with the connect function.
I solved it by changing the the java Plugin file removing the new thread creation:

I removed the blocks:
`new Thread() {
            public void run() {
...
          }
        }.start();
`
and put the thread code directly into the method body. It still seems to work.

Now the function is blocking and you can handle the asyncronicity directly in Flutter.

**Comment by Niek** [comment]
Same issue here

**Comment by mrm** [comment]
Appears to be be fixed in https://github.com/alternadom/WiFiFlutter/commit/d6ee47985a80dea6b5910463c93e257514028cc8.
