### ISSUE TITLE
I Fixed a bug: getClientList with onlyReachables=false, found device list but return empty

### ISSUE THREAD

**Issue by crifan** [alternadom/WiFiFlutter#37]
### bug

* test code:

```java
List<APClient> apClientList = await getClientList(false, 3000);
print("apClientList=$apClientList");
```

* expect result: list contain current really connected device list

* actual result:  empty list

* root cause:

in `WiFiFlutter/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java`, code is 

`if (client.isReachable() == finalOnlyReachables) {`

then process and return device list

but current value is:

* client.isReachable() -> true
* finalOnlyReachables -> false

so not return any device list.

### How to fix

`WiFiFlutter/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java`

change

`if (client.isReachable() == finalOnlyReachables) {`

to 

```java
Boolean shouldReturnCurrentClient = true;
if ( finalOnlyReachables.booleanValue()) {
    if (!clientIsReachable.booleanValue()){
        shouldReturnCurrentClient = Boolean.valueOf(false);
    }
}

if (shouldReturnCurrentClient.booleanValue()) {
```

for those onlyReachables=false, and found real device client.isReachable=true, then **CAN** return expected device list.

### what I want

please merge my fix into git src (to avoid others like me to spend many hours to figure out why return list is empty ), thanks.

**Comment by alternadom** [comment]
Please, make a pull request and I will accept it ;)
Thanks for your hard work and sorry for the labor!
