### ISSUE TITLE
[wifi_iot] WiFiForIoTPlugin.connect() 

### ISSUE THREAD

**Issue by Bojan227** [alternadom/WiFiFlutter#372]
```
Future<bool> handleDeviceConnection(ConnectionInfoDto connectionInfoDto) async {
  log('connect the device');

  final register = await WiFiForIoTPlugin.registerWifiNetwork(
    connectionInfoDto.ssid,
    security: NetworkSecurity.NONE,
  );

  log('$register - register');

  final response = await WiFiForIoTPlugin.connect(
    connectionInfoDto.ssid,
    joinOnce: true,
    security: NetworkSecurity.NONE,
    withInternet: false,
  );

  log("$response connection to the device");
  if (!response) {
    return false;
  } else {
    return await WiFiForIoTPlugin.forceWifiUsage(true);
  }
}
```

After await WiFiForIoTPlugin.connect is called a native andorid modal is present with the device being shown, but why does the call keep getting repeated unless I click connect or cancel. If I click connect after 2-3 seconds there will be another modal being shown that can destroy my app flow. Any ideas on how to handle this?
![wifi_iot](https://github.com/flutternetwork/WiFiFlutter/assets/80133862/c7978a2d-bb0e-4566-bea7-c709707ccdae)

**Comment by nari2442** [comment]
Same Issue here how to block those default popups

**Comment by nari2442** [comment]
@Bojan227  oh is it?? i think i already tried that as well but still getting those popups .
