### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [alternadom/WiFiFlutter#4]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by alternadom** [comment]
Hi,
No problem for your contribution, we are open for a free logo :)
Thanks,

**Comment by anharismail** [comment]
thank for your response @alternadom , I'll provide my logo proposal as soon as possible :)

**Comment by anharismail** [comment]
Hello @alternadom, why this issue was closed?

**Comment by alternadom** [comment]
Hi, I closed it because it is not an issue in my opinion!

**Comment by anharismail** [comment]
Can I still post my logo proposal here? @alternadom

**Comment by alternadom** [comment]
Yes you can, or you can send it directly to me by mail :)

**Comment by anharismail** [comment]
Hello, Sir @alternadom . These is my logo proposal for your project.
This logo was inspired by Flutter logo. I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

![wifi flutter ver 1](https://user-images.githubusercontent.com/37614260/41352098-a0f800a2-6f42-11e8-9b68-db12979b5191.png)

**Comment by alternadom** [comment]
Oh yeah! Nice job @anharismail, I like it :)
I prefer the colored version..

@yhua537, can you give us your opinion about it please ?

**Comment by alternadom** [comment]
Oh and @anharismail, AlternaDom is not a person but a French startup in IoT :)

**Comment by yhua537** [comment]
Like the colored version as well, it has almost the same color scheme as Flutter.

Personally, 3 bars + the dot is a bit too busy, taking one out looks better to me. 

Is AlternaDom's product open to for discussion? I am interested, pm me if ok to discuss.

**Comment by alternadom** [comment]
Yep, 2 bars + dot will be lighter ;)

@yhua537 , i pm you!

**Comment by anharismail** [comment]
Ah yes, they are on the same package. Since professional logo, it has to have black and white version.

Sorry, I'm think it's personal account. I just mention it as project owner :)

Anyway, this is the revision with 2 bars and one dot. @alternadom 

![wifi flutter ver 2](https://user-images.githubusercontent.com/37614260/41356438-1d7b7eaa-6f4e-11e8-8f31-e049d35c953d.png)

**Comment by yhua537** [comment]
That's real quick! Well done ^_^

**Comment by alternadom** [comment]
Good joob @anharismail ;) No problem for the id @ alternadom! ^^

**Comment by anharismail** [comment]
Thanks. By the way, what type of files and sizes you needed for the project? 

Can I make a pull request?

**Comment by alternadom** [comment]
I tried to pm you all but don't think it worked.. :(

Can you contact me on contact@alternadom.com please ?

**Comment by anharismail** [comment]
Hello @alternadom , I sent you a message on your email :)
