### ISSUE TITLE
WiFiForIoTPlugin.disconnect() in Android requires Location permission.

### ISSUE THREAD

**Issue by daadu** [alternadom/WiFiFlutter#40]
WiFiForIoTPlugin.disconnect() in Android requires Location permission, the plugin code for android does not check for the permission.

After enabling this permission manually from settings the method worked. I realized there is a bug here. Can someone confirm this? If confirmed I would like to file a PR for this.

**Comment by daadu** [comment]
I rechecked and it is working without permission,  something weird is happening. anyways closing this issue.

**Comment by zzzh** [comment]
> I rechecked and it is working without permission, something weird is happening. anyways closing this issue.

Hi, would you please tell me how you make it work?
Foe me, It returns true, but wifi is still connected.
