### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by Str4ight** [alternadom/WiFiFlutter#41]
Hello everyone,
It's a pleasure to find this work. I am new in Flutter and I want to make sure I can use for this particular feature. I came to meet this work I was wondering how I could integrate into a very basic flutter app just to make sure it can connect wifi. Actually, your README file doesn't explain the basic installation.
Thanks for your work

**Comment by Mohanedy98** [comment]
The same for me I also don't know how to integrate it into my project .. hope anyone provide a guide for it

**Comment by alternadom** [comment]
Sorry guys, I don't have time to make a guide for something like this :/

You can check this thread for the conf :
https://github.com/alternadom/WiFiFlutter/issues/11
