### ISSUE TITLE
(iOS) Missing swift version causes pod install error

### ISSUE THREAD

**Issue by Njuelle** [alternadom/WiFiFlutter#43]
Hello,

When I try to build with Xcode(v10.3) I get the following error:

```
 -> Installing wifi_iot (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:
    - `wifi_iot` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```
I try to add `s.swift_version = '4.0'` in your podspec config file and it fixed the problem :)

Also to be able to build my project in Xcode with your plugin I had to add the following line in my podfile : `use_frameworks!`

If you want, I can make a tiny pull request to add swift version (please tell me which version you are using) and update the readme to explain how to build on iOS

**Comment by alternadom** [comment]
Yeah thanks @Njuelle !

Do as you think it is good to be ;)

**Comment by Njuelle** [comment]
Pull request incoming ;)
