### ISSUE TITLE
forceWifiUsage issues

### ISSUE THREAD

**Issue by Nico04** [alternadom/WiFiFlutter#46]
I recently needed to use the Android function bindProcessToNetwork for phones that allow to be connected to mobile data AND wifi at the same time, to force the OS to use the wifi for my iot requests, in the process of replacing an Xamarin.Forms app to a Flutter one. 
In this process I ended up editing your plugin, so here my notes :
1. Why you open the `Settings.ACTION_MANAGE_WRITE_SETTINGS` window ? From my tests and after reading the Android documentation, none of the used function in this method needs it...
2. The Dart function `WiFiForIoTPlugin.forceWifiUsage(`) doesn't return a Future like the other ones, so it cannot be awaited, which is quite anoying.
3. Why using `manager.requestNetwork(builder.build(), new ConnectivityManager.NetworkCallback() {})`, when you could just use `manager.getAllNetworks()` ? I guess this is the cause of not beeing able to return a future.

Here is my final modification for the WifiIotPlugin.java file :
```
    private void forceWifiUsage(MethodCall poCall, Result poResult) {
        //boolean canWriteFlag = false;

        boolean useWifi = poCall.argument("useWifi");

        if (useWifi) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                final ConnectivityManager manager = (ConnectivityManager) moContext
                        .getSystemService(Context.CONNECTIVITY_SERVICE);

                // get wifi network
                final Network[] networks = manager.getAllNetworks();
                Network network = null;
                for (Network n : networks) {
                    //getNetworkInfo() is  deprecated in API level 29, see https://developer.android.com/reference/android/net/ConnectivityManager.html#getNetworkInfo(android.net.Network)
                    //getType() is deprecated in API 28, see https://developer.android.com/reference/android/net/NetworkInfo.html#getType()
                    if (manager.getNetworkInfo(n).getType() == ConnectivityManager.TYPE_WIFI) {
                        network = n;
                        break;
                    }
                }

                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    manager.bindProcessToNetwork(network);
                } else {
                    ConnectivityManager.setProcessDefaultNetwork(network);
                }
            }
        } else {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                ConnectivityManager manager = (ConnectivityManager) moContext
                        .getSystemService(Context.CONNECTIVITY_SERVICE);
                assert manager != null;
                manager.bindProcessToNetwork(null);
            } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                ConnectivityManager.setProcessDefaultNetwork(null);
            }
        }
        
        poResult.success(null);
    }
```

This was tested on a P30 Pro phone, running Android 9.0.

I hope it will help.

**Comment by Nailik** [comment]
I just made a fork to add these changes and i can confirm that it's working on Android 9.0 (LineageOs, MiMix2) .
Thank you, much better for usability.
