### ISSUE TITLE
I want to connect automatically to WIFI on opening  my app. I did the following code but it is asking for modify system settings permission and alertbox to allow with message "App is trying to set WIFI on or off" again and again until I get output after connection. What to change to avoid this pop up and change system settings permission alert box coming again and again ?

### ISSUE THREAD

**Issue by flutterLearner** [alternadom/WiFiFlutter#49]
@override
Widget build(BuildContext context){

final defaultTheme =Theme.of(context);

if(defaultTheme.platform==TargetPlatform.android){

IsEnabled();
If(_IsEnabled!=null && _IsEnabled)
{ 
isConnected();
If(_isConnected != null && _isConnected)
{
getBSSID();
print("found bssid : $bssid");
}else{
WifiIoTPlugin.forceWifiUsage(true);
isConnected();
}
}else {
   WiFiForIoTPlugin.setEnabled(true);
}
}
}

**Comment by alternadom** [comment]
Hi,

Don't need to spam our contact mail 10 minutes after posting here.. 
Your problem seems to be the permissions file, not the plugin!

Check permissions for Android or iOS ;)

PS : Make more readable post.. thanks!
