### ISSUE TITLE
How to set SSID and PASSWORD fot Access Point?

### ISSUE THREAD

**Issue by paulotolentino** [alternadom/WiFiFlutter#57]
Hello,

I'm trying to set ssid for access point by sending some ssid using this method `WiFiForIoTPlugin.setWiFiAPSSID("someSSID");`
But I'm getting this log:

`E/flutter (26192): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to write to field 'java.lang.String android.net.wifi.WifiConfiguration.SSID' on a null object reference, null)`
`E/flutter (26192): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)`
`E/flutter (26192): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)`
`E/flutter (26192): <asynchronous suspension>`
`E/flutter (26192): #2      WiFiForIoTPlugin.setWiFiAPSSID (package:wifi_iot/wifi_iot.dart:111:22)`
`E/flutter (26192): #3      _FlutterWifiIoTState.getButtonWidgetsForAndroid.<anonymous closure> (package:wifi_iot_example/main.dart:503:32)`
`E/flutter (26192): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)`
`E/flutter (26192): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)`
`E/flutter (26192): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)`
`E/flutter (26192): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)`
`E/flutter (26192): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)`
`E/flutter (26192): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)`
`E/flutter (26192): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)`
`E/flutter (26192): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)`
`E/flutter (26192): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)`
`E/flutter (26192): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)`
`E/flutter (26192): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)`
`E/flutter (26192): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)`
`E/flutter (26192): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)`
`E/flutter (26192): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)`
`E/flutter (26192): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)`
`E/flutter (26192): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)`
`E/flutter (26192): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)`
`E/flutter (26192): #21     _rootRunUnary (dart:async/zone.dart:1138:13)`
`E/flutter (26192): #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)`
`E/flutter (26192): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)`
`E/flutter (26192): #24     _invoke1 (dart:ui/hooks.dart:273:10)`
`E/flutter (26192): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)`

I don't now how to fix it. Can someone help me? Can be the same question for other guys.

**Comment by alternadom** [comment]
`Unhandled Exception: PlatformException(error, Attempt to write to field 'java.lang.String android.net.wifi.WifiConfiguration.SSID' on a null object reference, null)`

The answer is here..
