### ISSUE TITLE
Problem using the plugin.

### ISSUE THREAD

**Issue by josediegopassos** [alternadom/WiFiFlutter#59]
Hello!

I am unable to use the dependency published in 'https://pub.dev/packages/wifi_iot' in my project.

Is there any other step I should take?

I was also unable to run your example.

**Comment by julienrbrt** [comment]
Do you have more information about your issue?

**Comment by josediegopassos** [comment]
Now I was able to install it without any problems!
The library is working perfectly!
Congratulations on the work!
