### ISSUE TITLE
Doesn't work with Android targetSdk 29

### ISSUE THREAD

**Issue by itsJoKr** [alternadom/WiFiFlutter#60]
Hey. Android SDK 29 comes with a lot of changes with wifi, mainly so that the user is in more control and the app can't silently manage wifi.

For some actions, the app needs to open settings panel in the bottom sheet (e.g. turning on wifi, so that the user finishes the action). I think some of the actions that are now possible will not be possible at all. It would be good to update the library for this.

**Comment by daadu** [comment]
Fix for this issue is being work on at #88.

Recommend you to test/review it and provide feedback (instruction are in the PR itself). Merging of #88 will close this issue as well.

**Comment by daadu** [comment]
@itsJoKr Can you test/review the PR #88 (details in description of PR)? Merging the PR will close this issue.

**Comment by itsJoKr** [comment]
Hey. I'm not working with this yet. At the time I was evaluating it for the future project and saw that it doesn't support newest Android WiFi shenanigans.

PR looks good, thank you for your hard work. We can close the issue.
