### ISSUE TITLE
Trying to connect to Wifi with example app crashes the app entirely (iOS 13.3.1)

### ISSUE THREAD

**Issue by DataGrump** [alternadom/WiFiFlutter#61]
It crashes without the ability to try/catch. I think it kills the entire framework.
Library is unusable for iOS 13.3.1 at least.

**Comment by flukejones** [comment]
I have an outdated phone on 12.4.x for testing and it also crashes on wifi scan.

**Comment by flukejones** [comment]
Was missing permissions for lcoation. But now have a new issue (wifi_scan not method not implemented for ios I guess).
