### ISSUE TITLE
App crash when use launch WiFiForIoTPlugin.connect()

### ISSUE THREAD

**Issue by gfucka** [alternadom/WiFiFlutter#64]
As in the object when I launch WiFiForIoTPlugin.connect() app crash.
I'm using flutter 1.12.3+hotfix.5 and targetSdk 28.
Thank you

**Comment by aarenstade** [comment]
Hello, I have the same exact problem.
Moved code and packages to a new project and this error appeared.
I tried adding error catching in the connect function but the app still crashes.

I'm running on an ios device with Flutter 1.17.4

What's the best way to debug this problem and catch this error?

**Comment by luccasmaso** [comment]
Same happening here...

<img width="1578" alt="Screenshot 2020-09-24 at 17 15 30" src="https://user-images.githubusercontent.com/1427231/94195565-8d21d200-fe89-11ea-805b-aa9288a6ef3d.png">

**Comment by daadu** [comment]
Do you find this issue with latest pub version? It could be because of android-embedding-v1 used in older pub version (0.1.x series)

**Comment by daadu** [comment]
Closing this issue, since no response. Feel free to request re-opening of it.
