### ISSUE TITLE
How to connect to a hidden network?

### ISSUE THREAD

**Issue by ConProgramming** [alternadom/WiFiFlutter#68]
Hi, this library works great on publicly visible networks but I'm having trouble finding how to connect to a hidden network?

**Comment by alternadom** [comment]
If it's hidden, you can't scan it.. maybe there is an update here!

**Comment by ZhuXiaolong33** [comment]
I also have trouble finding how to connect to a hidden network?

**Comment by IskanderA1** [comment]
use my fork https://github.com/IskanderA1/WiFiFlutter

**Comment by daadu** [comment]
@IskanderA1 If working can you file PR with this feature?

**Comment by BillMac4440** [comment]
Thanks for the work everyone!, but I need the combination of the withInternet and isHidden when it all gets merged together.
Then the IoT device config will work great.

**Comment by BillMac4440** [comment]
@IskanderA1 Is it possible to get your fork in sync with the "withInternet" branch?  I think I need both fixes.  IoT device with soft AP with no internet access and it is a hidden SSID.  You connect to the soft AP and do a REST API to put it on a network.  Got all working but connect to a hidden SSID.

**Comment by IskanderA1** [comment]
@BillMac4440 yse, of course

**Comment by daadu** [comment]
@IskanderA1 File PR if the feature is ready.

**Comment by daadu** [comment]
@IskanderA1 I have cherry-picked form @IskanderA1 fork at #145 .

@IskanderA1  @BillMac4440   Please review the changes.

**Comment by daadu** [comment]
This fix/feature has landed with [v0.3.3 on pub.dev](https://pub.dev/packages/wifi_iot/versions/0.3.3).
