### ISSUE TITLE
获取wifi列表需要开启GPS才能正常得到   You need to turn on GPS to get WiFi list。Why？

### ISSUE THREAD

**Issue by ZCHUANGJie** [alternadom/WiFiFlutter#70]
在开发时使用此插件获取附近wifi列表时，为什么需要开启手机GPS定位功能才能正常获取呢？目前无解决方法！！！！！
When using this plug-in to obtain the nearby WiFi list during development, why do you need to turn on the GPS positioning function of the mobile phone to get it normally? There is no solution at present!!!!!

**Comment by shashikantdurge** [comment]
It is android requirement.

**Comment by ZCHUANGJie** [comment]
只有android手机会是吧，那有解决的方法吗？Only android phones will be. Is there a solution?

**Comment by shashikantdurge** [comment]
https://developer.android.com/training/connect-devices-wirelessly/wifi-direct#permissions

> In order to use Wi-Fi P2P, add the ACCESS_FINE_LOCATION, CHANGE_WIFI_STATE, ACCESS_WIFI_STATE, and INTERNET permissions to your manifest.
