### ISSUE TITLE
WiFiForIoTPlugin.loadWifiList() not retriewing result (Android 10)

### ISSUE THREAD

**Issue by andzejsw** [alternadom/WiFiFlutter#72]
I tried to get Wifi scan results on my Android 10 Samsung S10+ device, but there is no result retrieved on Fututre.
My code: 
```
    List<WifiNetwork> scanResult = await WiFiForIoTPlugin.loadWifiList();
    print("AppSettings scanResult $scanResult");
```

**Comment by andzejsw** [comment]
Fix was simple, but very hard to find. We need to ask location permission only from app code, not package. For example i did this: 

```
   bool hasPermission = await PermissionsService().hasPermission(PermissionGroup.location);
    if (!hasPermission) {
      bool granted = await PermissionsService().requestPermission(PermissionGroup.location);
      if(granted) {
        print("AppSettings before loadWifiList");
        WiFiForIoTPlugin.setEnabled(true);
        var list = await WiFiForIoTPlugin.loadWifiList();
        print("AppSettings _showWifiSelectDialogWithPermissionCheck :) $list");
      } else {
        // Show rejected scenario
      }
    } else {
      print("AppSettings before loadWifiList");
      WiFiForIoTPlugin.setEnabled(true);
      var list = await WiFiForIoTPlugin.loadWifiList();
      print("AppSettings _showWifiSelectDialogWithPermissionCheck :) $list");
    }
```

**Comment by alternadom** [comment]
Thanks @andzejsw for you hard work!

If you want, you could make a pull request, we will accept it from our side ;)

Have a nice day,

**Comment by ali80** [comment]
@andzejsw's solution didnt fix it for me,
`loadWifiList` future never completes for me on one of my devices.
I have tested on two android devices, one running android 11 that works fine
the one running android 9 which has this problem!

**Comment by daadu** [comment]
@ali80 I have passed a working code at https://github.com/alternadom/WiFiFlutter/issues/184. Please check it.
