### ISSUE TITLE
isConnected returning always false but the Phone connected successfully to the wifi

### ISSUE THREAD

**Issue by felixsmart** [alternadom/WiFiFlutter#75]
Hi there,

I'm testing and the module works perfect with iOS. 

I'm now testing an Android (Using a Xiaomi M10) and this always returns false. The issue is that the Android Phone connected successfully to the Wifi (I can see it is connected).

bool isConnected = await WiFiForIoTPlugin.connect(STA_DEFAULT_SSID,
        password: STA_DEFAULT_PASSWORD,
        joinOnce: false,
        security: NetworkSecurity.WPA);

Any ideas?

**Comment by cool-518** [comment]
same problem!

**Comment by bigbirdhzp** [comment]
i hava the same problem!!!

**Comment by qhu91it** [comment]
Me too, Pixel XL android 10

**Comment by pyon123** [comment]
In my case, Android is working fine, but not working in iOS.
Would you like to explain me how you implement it in iOS?

**Comment by daadu** [comment]
`isConnected` is not working because of new restrictions added by iOS (not returning current SSID, based on which `isConnected` works). Issue  #142 is tracking this change and it's fix. PR is most welcomed.

**Comment by daadu** [comment]
The fix has landed on pub.dev with v0.3.4.

@felixsmart  Thanks for filing this bug. Check yourself in README!!

**Comment by lgozalvez** [comment]
> The fix has landed on pub.dev with v0.3.4.
> 
> @felixsmart Thanks for filing this bug. Check yourself in README!!

Amazing!, Thanks (I'm the CTO of Felix Smart)

**Comment by usmanNoor5** [comment]
same problem
