### ISSUE TITLE
Can't get Wifi Access Point Infos in android version 8.0.0 and 9

### ISSUE THREAD

**Issue by jeffrey0606** [alternadom/WiFiFlutter#84]
This is the error message i'm getting:
E/class info.whitebyte.hotspotmanager.WifiApManager(11444): Caused by: java.lang.SecurityException: App not allowed to read or update stored WiFi Ap config (uid = 10086)

**Comment by daadu** [comment]
Where you testing on emulator? Android Emulator does not support Hotspot.

**Comment by jeffrey0606** [comment]
> Where you testing on emulator? Android Emulator does not support Hotspot.

yeah i tested on my emulator of android version 8 an it does not work obviously but i tested it on my phone with android version 9. now i wrote a kotlin code that manages just the on/off the hotspot.

**Comment by daadu** [comment]
Close this issue if it is not an actual issue!
