### ISSUE TITLE
Getting 'wifi_iot/wifi_iot-Swift.h' file not found when "flutter build ios"

### ISSUE THREAD

**Issue by KnowLedgeWat** [alternadom/WiFiFlutter#91]
Getting 'wifi_iot/wifi_iot-Swift.h' file not found when "flutter build iOS"

Xcode's output:
↳
    /Users/MDM/Developer/flutter/.pub-cache/git/wifi_iot-bd17a8cfdac3ad8f3e0e78032902e6a30caaef38/ios/Classes/WifiIotPlugin.m:2:9: fatal error:
    'wifi_iot/wifi_iot-Swift.h' file not found
    #import <wifi_iot/wifi_iot-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

Using Flutter 1.22.3 and building for iOS. Can you help? If necessary I can add more information.

**Comment by daadu** [comment]
@KnowLedgeWat Are you still facing this issue in latest pub version. Request you to close this issue, if not a problem anymore.

**Comment by daadu** [comment]
Closing this issue, since no response. Feel free to request re-opening of it.
