### ISSUE TITLE
Can't seem to get this working on iOS

### ISSUE THREAD

**Issue by ominibyte** [alternadom/WiFiFlutter#92]
Is anyone using this on iOS?
Can't seem to get WiFiForIoTPlugin.connect to go through on iOS. Tried it on iOS 12.x and 14.x.

I can't find any documentation on steps to take to verify if I'm doing something wrong.

Any help is appreciated.

**Comment by krishnaaro** [comment]
WiFiForIoTPlugin.findAndConnect(), works on ios 14.x ?? @ominibyte @daadu

**Comment by ominibyte** [comment]
Use WiFiForIoTPlugin.connect for iOS. Tested on 14.1.
