### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by diegotori** [alternadom/WiFiFlutter#96]
@alternadom is there any chance that you can please publish a new release to [pub.dev](https://pub.dev/packages/wifi_iot)? Right now, it hasn't been updated in over 10 months. Given the latest changes merged into this repo recently, I think this should warrant a new version (0.2.0). Please let me know your thoughts on this so that I can update my current app with this version that fixes #60, #80, and #94.

Thank you in advance.

**Comment by alternadom** [comment]
Hi there!

I'm not in that kind of subject since a few months.. i don't even remember how to do that :( 

We are looking for persons who can take the relay!

**Comment by diegotori** [comment]
https://dart.dev/tools/pub/publishing. If you want, I can take on the role of publishing. Since you're a verified publisher according to pub.dev, you can also add folks that could [upload new releases](https://dart.dev/tools/pub/cmd/pub-uploader) on your behalf.

**Comment by diegotori** [comment]
Also, you should designate a couple of people here as Maintainers so that they can merge code on your behalf and run the day to day operations on this project. You can also add them as pub uploaders as well to that effect so that you add redundancy in terms of who can upload.

**Comment by alternadom** [comment]
For the people interested, please send me a private message and give me your Gmail address ;)

Thanks for your advice @diegotori

**Comment by diegotori** [comment]
@alternadom looks like GitHub doesn't support private messaging. Therefore you may need to list your email address on your profile so that people can email you directly.

**Comment by alternadom** [comment]
Just contact us via our form on our website so ;)

**Comment by diegotori** [comment]
@alternadom Managed to do just that. Please lemme know if you received a message to that effect, since it has my Gmail address. Thanks in advance.

**Comment by alternadom** [comment]
Hi,
I received @daadu & @diegotori , I will do that (hopefully) today!

**Comment by alternadom** [comment]
I'm facing this issue :

`Package "wifi_iot" is owned by publisher "alternadom.com". Updating the uploaders is not permitted.
`
:(

**Comment by alternadom** [comment]
Seems that being "publisher" don't give possibility to add uploader.. so I added @daadu to admin on our publisher! 
If you find something to let you publish without admin access, tell us ;)

**Comment by diegotori** [comment]
@daadu seeing that you are now the new admin for this project on pub.dev, can you please upload a new version? Thanks in advance.

**Comment by diegotori** [comment]
@alternadom based on this change (https://github.com/dart-lang/pub-dev/pull/4195), looks like adding an admin to the publisher automatically grants that person uploader rights. tl;dr: I think you have to add folks as admins in order for them to upload.

**Comment by alternadom** [comment]
I just have this...

https://www.alternadom.com/wp-content/uploads/2020/11/Capture-décran-2020-11-26-à-14.30.28.png

**Comment by daadu** [comment]
@alternadom Looks like my permissions are revoked. Getting following error while publishing from my account.

<img width="509" alt="Screenshot 2020-11-26 at 10 57 16 PM" src="https://user-images.githubusercontent.com/4963236/100379411-dbdf1a00-303a-11eb-9eb1-c98c97c3bf6d.png">

**Comment by daadu** [comment]
You can add new member to pub.dev publisher by going "My pub.dev" -> "alternadom.com" -> "Admin" -> "Add Member"

**Comment by alternadom** [comment]
I wanted to give access to publish on wifi_iot to you and @diegotori , except that I could'nt.. 
I just can give you full access (admin) to our "publisher" (what I did). 
So you can publish wifi_iot and other we can develop in the future :( 
The rules are not really easy to understand on pub.dev...

**Comment by diegotori** [comment]
I think the next step is to ask a question in https://github.com/dart-lang/pub-dev.

**Comment by diegotori** [comment]
@alternadom and @daadu, asked the following question to pub-dev: https://github.com/dart-lang/pub-dev/issues/4303. Hopefully we'll get an answer soon enough.

**Comment by daadu** [comment]
@diegotori @alternadom Ooops! The issue was not accepting the invitation before publishing.

**Comment by daadu** [comment]
And AFA "admin" privileges is concerned that gives rights to publish new or update exiting packages under the publisher. We cannot do much about it. Hope pub.dev adds this feature to give package level permissions.

**Comment by daadu** [comment]
Congrats. v0.2.0 is published to pub.dev.

**Comment by daadu** [comment]
@diegotori Close this issue if things are resolved and also close the issue opened on pub-dev repo.

**Comment by diegotori** [comment]
Can confirm that version 0.2.0 is live on pub.dev. Thanks @daadu for updating it.
