### ISSUE TITLE
[android] registerNetwork for Android 29+

### ISSUE THREAD

**Issue by daadu** [alternadom/WiFiFlutter#98]
use `ACTION_WIFI_ADD_NETWORK` API - [doc](https://developer.android.com/guide/topics/connectivity/wifi-save-network-passpoint-config)

**Comment by Niek** [comment]
+1

**Comment by daadu** [comment]
@Niek Can you help implementing this? I have added doc links about it.

**Comment by fedepell** [comment]
@daadu : What would be the idea of this ticket? To add a new method `registerNetwork(SSID, authType, passphrase)` that launches an intent `ACTION_WIFI_ADD_NETWORK` with the suggestion based on the SSID/authType,passphrase?

**Comment by daadu** [comment]
Yes, I think we will have to add new method, I suggest `registerWifiNetwork(Strring ssid, String password, NetworkSecurity security);` another option is to add flag (lets say - `shouldRegister`) in `connect` and `findAndConnect` methods.

**Comment by fedepell** [comment]
I have just created PR #113 with a proposal. It supports basic wireless network suggestions and, parametrized, also permanent saving via `ACTION_WIFI_ADD_NETWORK` intent (only API >= 30).

I'm rather new to this plugin and Flutter, so any comment is more than welcome. I did directly a PR as it is probably easier to discuss this way.

**Comment by daadu** [comment]
This has landed in [v0.2.1 on pub.dev](https://pub.dev/packages/wifi_iot/versions/0.2.1), do check it out. Thank you @fedepell  for your contribution to this package.
